server:
  port: 8086
spring:
  application:
    name: sms-server
  rabbitmq:
    host: 192.168.11.129
    username: leyou
    password: leyou
    virtual-host: /leyou
ly:
  sms:
    accessKeyID: LTAI4Fjv1jh6bhjiNpqyKBT2 # 你自己的accessKeyId
    accessKeySecret: XhtG83jt1j90iYyKqGbIx7sRBur9wx # 你自己的AccessKeySecret
    signName: 传智健康 # 签名名称
    verifyCodeTemplate: SMS_177241040 # 模板名称
    domain: dysmsapi.aliyuncs.com # 域名
    action: SendSMS # API类型，发送短信
    version: 2017-05-25 # API版本，固定值
    regionID: cn-hangzhou # 区域id