server:
  port: 8083
spring:
  application:
    name: search-service
  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: 192.168.11.129:9300
  rabbitmq:
    host: 192.168.11.129
    username: leyou
    password: leyou
    virtual-host: /leyou
  redis:
    host: 192.168.11.129
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15
logging:
  level:
    com.leyou.search: debug
    org.springframework: debug
